#Requires -Version 7.0
#Requires -Modules Microsoft.Graph.Authentication, Microsoft.Graph.Applications

<#
.SYNOPSIS
    Creates Entra ID app registrations for MCP Enterprise Auth project.

.DESCRIPTION
    Idempotently creates 8 app registrations in Microsoft Entra ID:
    - 1 MCP Server Resource API (with exposed scopes and app roles)
    - 5 Public clients (VS Code, Claude Desktop, Claude Code, ChatGPT, Generic)
    - 1 Confidential client (with client secret)
    - 1 Service Principal (with client secret and app role assignment)

    The script generates a .env file with all configuration values needed
    to run the MCP server and client examples.

.PARAMETER TenantId
    The Entra ID tenant ID. If not provided, will use the signed-in user's tenant.

.PARAMETER OutputEnvFile
    Path to output .env file. Defaults to repository root (.env).

.PARAMETER Force
    Force recreation of client secrets even if apps already exist.

.PARAMETER AppNamePrefix
    Prefix for app registration names. Defaults to "MCP".

.EXAMPLE
    .\Setup-EntraIdAppRegistrations.ps1
    Creates all app registrations using interactive authentication.

.EXAMPLE
    .\Setup-EntraIdAppRegistrations.ps1 -TenantId "12345678-1234-1234-1234-123456789abc"
    Creates app registrations in the specified tenant.

.EXAMPLE
    .\Setup-EntraIdAppRegistrations.ps1 -Force
    Recreates client secrets for existing apps.

.NOTES
    Requires Global Administrator or Application Administrator role.
    Required Microsoft Graph modules:
    - Microsoft.Graph.Authentication
    - Microsoft.Graph.Applications

    Install with: Install-Module Microsoft.Graph -Scope CurrentUser
#>

[CmdletBinding()]
param(
    [Parameter()]
    [string]$TenantId,

    [Parameter()]
    [string]$OutputEnvFile,

    [Parameter()]
    [switch]$Force,

    [Parameter()]
    [string]$AppNamePrefix = "MCP"
)

# Script-level variables for scope/role IDs
$script:McpReadScopeId = $null
$script:McpWriteScopeId = $null
$script:McpReadAllRoleId = $null
$script:McpReadWriteAllRoleId = $null

# =============================================================================
# Helper Functions
# =============================================================================

function Write-Status {
    param(
        [string]$Message,
        [ValidateSet("Info", "Success", "Warning", "Error")]
        [string]$Type = "Info"
    )

    $colors = @{
        "Info"    = "Cyan"
        "Success" = "Green"
        "Warning" = "Yellow"
        "Error"   = "Red"
    }

    Write-Host $Message -ForegroundColor $colors[$Type]
}

function Get-OrCreateApplication {
    <#
    .SYNOPSIS
        Gets an existing app registration or creates a new one.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$DisplayName,

        [Parameter()]
        [hashtable]$AppDefinition
    )

    # Search for existing app by displayName
    $existingApps = Get-MgApplication -Filter "displayName eq '$DisplayName'" -ErrorAction SilentlyContinue

    if ($existingApps -and $existingApps.Count -gt 0) {
        Write-Status "Found existing app: $DisplayName" -Type Warning
        return @{
            Application = $existingApps[0]
            Created     = $false
        }
    }

    # Create new application
    Write-Status "Creating app: $DisplayName" -Type Info
    $newApp = New-MgApplication @AppDefinition

    Write-Status "Created app: $DisplayName (AppId: $($newApp.AppId))" -Type Success
    return @{
        Application = $newApp
        Created     = $true
    }
}

function Ensure-ServicePrincipal {
    <#
    .SYNOPSIS
        Ensures a service principal exists for an application.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$AppId
    )

    # Check if service principal exists
    $sp = Get-MgServicePrincipal -Filter "appId eq '$AppId'" -ErrorAction SilentlyContinue

    if (-not $sp) {
        Write-Status "Creating service principal for app: $AppId" -Type Info
        $sp = New-MgServicePrincipal -AppId $AppId
    }

    return $sp
}

function Add-ClientSecret {
    <#
    .SYNOPSIS
        Adds a client secret to an application.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$AppObjectId,

        [Parameter()]
        [string]$Description = "Auto-generated by setup script",

        [Parameter()]
        [int]$ValidityDays = 365
    )

    $passwordCredential = @{
        displayName = $Description
        endDateTime = (Get-Date).AddDays($ValidityDays)
    }

    $secret = Add-MgApplicationPassword -ApplicationId $AppObjectId -PasswordCredential $passwordCredential

    return $secret.SecretText
}

# =============================================================================
# App Registration Functions
# =============================================================================

function New-McpServerResource {
    <#
    .SYNOPSIS
        Creates the MCP Server Resource API application.
    #>
    param(
        [string]$Prefix
    )

    $displayName = "$Prefix Server Resource"
    $appIdUri = "api://mcp-server-resource"

    # Generate unique GUIDs for scopes and roles
    $readScopeId = [Guid]::NewGuid().ToString()
    $writeScopeId = [Guid]::NewGuid().ToString()
    $readAllRoleId = [Guid]::NewGuid().ToString()
    $readWriteAllRoleId = [Guid]::NewGuid().ToString()

    # Check if app already exists
    $existingApp = Get-MgApplication -Filter "displayName eq '$displayName'" -ErrorAction SilentlyContinue
    if ($existingApp) {
        Write-Status "Found existing app: $displayName" -Type Warning

        # Extract existing scope/role IDs
        if ($existingApp.Api.Oauth2PermissionScopes) {
            $readScope = $existingApp.Api.Oauth2PermissionScopes | Where-Object { $_.Value -eq "mcp.read" }
            $writeScope = $existingApp.Api.Oauth2PermissionScopes | Where-Object { $_.Value -eq "mcp.write" }
            if ($readScope) { $readScopeId = $readScope.Id }
            if ($writeScope) { $writeScopeId = $writeScope.Id }
        }
        if ($existingApp.AppRoles) {
            $readAllRole = $existingApp.AppRoles | Where-Object { $_.Value -eq "MCP.Read.All" }
            $readWriteAllRole = $existingApp.AppRoles | Where-Object { $_.Value -eq "MCP.ReadWrite.All" }
            if ($readAllRole) { $readAllRoleId = $readAllRole.Id }
            if ($readWriteAllRole) { $readWriteAllRoleId = $readWriteAllRole.Id }
        }

        # Store in script scope
        $script:McpReadScopeId = $readScopeId
        $script:McpWriteScopeId = $writeScopeId
        $script:McpReadAllRoleId = $readAllRoleId
        $script:McpReadWriteAllRoleId = $readWriteAllRoleId

        $sp = Ensure-ServicePrincipal -AppId $existingApp.AppId

        return @{
            Application      = $existingApp
            ServicePrincipal = $sp
            Created          = $false
        }
    }

    # Store IDs in script scope for client registrations
    $script:McpReadScopeId = $readScopeId
    $script:McpWriteScopeId = $writeScopeId
    $script:McpReadAllRoleId = $readAllRoleId
    $script:McpReadWriteAllRoleId = $readWriteAllRoleId

    # Define exposed API scopes (delegated permissions)
    $oauth2PermissionScopes = @(
        @{
            Id                      = $readScopeId
            AdminConsentDescription = "Read MCP resources"
            AdminConsentDisplayName = "Read MCP resources"
            UserConsentDescription  = "Read MCP resources on your behalf"
            UserConsentDisplayName  = "Read MCP resources"
            IsEnabled               = $true
            Type                    = "User"
            Value                   = "mcp.read"
        },
        @{
            Id                      = $writeScopeId
            AdminConsentDescription = "Write MCP resources"
            AdminConsentDisplayName = "Write MCP resources"
            UserConsentDescription  = "Write MCP resources on your behalf"
            UserConsentDisplayName  = "Write MCP resources"
            IsEnabled               = $true
            Type                    = "User"
            Value                   = "mcp.write"
        }
    )

    # Define app roles (application permissions)
    $appRoles = @(
        @{
            Id                 = $readAllRoleId
            AllowedMemberTypes = @("Application")
            Description        = "Read-only access to MCP resources"
            DisplayName        = "MCP Read All"
            IsEnabled          = $true
            Value              = "MCP.Read.All"
        },
        @{
            Id                 = $readWriteAllRoleId
            AllowedMemberTypes = @("Application")
            Description        = "Full read/write access to MCP resources"
            DisplayName        = "MCP ReadWrite All"
            IsEnabled          = $true
            Value              = "MCP.ReadWrite.All"
        }
    )

    Write-Status "Creating app: $displayName" -Type Info

    $app = New-MgApplication `
        -DisplayName $displayName `
        -SignInAudience "AzureADMyOrg" `
        -IdentifierUris @($appIdUri) `
        -Api @{
        Oauth2PermissionScopes      = $oauth2PermissionScopes
        RequestedAccessTokenVersion = 2
    } `
        -AppRoles $appRoles

    Write-Status "Created app: $displayName (AppId: $($app.AppId))" -Type Success

    # Ensure service principal exists
    $sp = Ensure-ServicePrincipal -AppId $app.AppId

    return @{
        Application      = $app
        ServicePrincipal = $sp
        Created          = $true
    }
}

function New-PublicMcpClient {
    <#
    .SYNOPSIS
        Creates a public client app registration.
    #>
    param(
        [Parameter(Mandatory)]
        [string]$DisplayName,

        [Parameter(Mandatory)]
        [string[]]$RedirectUris,

        [Parameter(Mandatory)]
        [string]$McpServerAppId
    )

    $appDefinition = @{
        DisplayName              = $DisplayName
        SignInAudience           = "AzureADMyOrg"
        PublicClient             = @{
            RedirectUris = $RedirectUris
        }
        IsFallbackPublicClient   = $true
        RequiredResourceAccess   = @(
            @{
                ResourceAppId  = $McpServerAppId
                ResourceAccess = @(
                    @{
                        Id   = $script:McpReadScopeId
                        Type = "Scope"
                    },
                    @{
                        Id   = $script:McpWriteScopeId
                        Type = "Scope"
                    }
                )
            }
        )
    }

    return Get-OrCreateApplication -DisplayName $DisplayName -AppDefinition $appDefinition
}

function New-ConfidentialMcpClient {
    <#
    .SYNOPSIS
        Creates a confidential client app registration with client secret.
    #>
    param(
        [Parameter(Mandatory)]
        [string]$Prefix,

        [Parameter(Mandatory)]
        [string]$McpServerAppId,

        [Parameter()]
        [switch]$ForceNewSecret
    )

    $displayName = "$Prefix Confidential Client"

    $appDefinition = @{
        DisplayName            = $displayName
        SignInAudience         = "AzureADMyOrg"
        Web                    = @{
            RedirectUris = @(
                "http://localhost:8080/callback",
                "http://localhost:3000/callback",
                "http://127.0.0.1:8080/callback"
            )
        }
        IsFallbackPublicClient = $false
        RequiredResourceAccess = @(
            @{
                ResourceAppId  = $McpServerAppId
                ResourceAccess = @(
                    @{
                        Id   = $script:McpReadScopeId
                        Type = "Scope"
                    },
                    @{
                        Id   = $script:McpWriteScopeId
                        Type = "Scope"
                    }
                )
            }
        )
    }

    $result = Get-OrCreateApplication -DisplayName $displayName -AppDefinition $appDefinition

    # Create client secret if new app or force flag
    $secret = $null
    if ($result.Created -or $ForceNewSecret) {
        Write-Status "Generating client secret for: $displayName" -Type Info
        $secret = Add-ClientSecret -AppObjectId $result.Application.Id -Description "MCP Confidential Client Secret"
    }

    return @{
        Application  = $result.Application
        ClientSecret = $secret
        Created      = $result.Created
    }
}

function New-ServicePrincipalMcpClient {
    <#
    .SYNOPSIS
        Creates a service principal client app registration with app role assignment.
    #>
    param(
        [Parameter(Mandatory)]
        [string]$Prefix,

        [Parameter(Mandatory)]
        [string]$McpServerAppId,

        [Parameter()]
        [switch]$ForceNewSecret
    )

    $displayName = "$Prefix Service Principal Client"

    $appDefinition = @{
        DisplayName            = $displayName
        SignInAudience         = "AzureADMyOrg"
        IsFallbackPublicClient = $false
        RequiredResourceAccess = @(
            @{
                ResourceAppId  = $McpServerAppId
                ResourceAccess = @(
                    @{
                        Id   = $script:McpReadWriteAllRoleId
                        Type = "Role"  # Application permission (not Scope)
                    }
                )
            }
        )
    }

    $result = Get-OrCreateApplication -DisplayName $displayName -AppDefinition $appDefinition

    # Create client secret if new app or force flag
    $secret = $null
    if ($result.Created -or $ForceNewSecret) {
        Write-Status "Generating client secret for: $displayName" -Type Info
        $secret = Add-ClientSecret -AppObjectId $result.Application.Id -Description "MCP Service Principal Secret"
    }

    # Ensure service principal exists
    $sp = Ensure-ServicePrincipal -AppId $result.Application.AppId

    return @{
        Application      = $result.Application
        ServicePrincipal = $sp
        ClientSecret     = $secret
        Created          = $result.Created
    }
}

function Grant-AppRoleAssignment {
    <#
    .SYNOPSIS
        Grants an app role assignment (admin consent for application permission).
    #>
    param(
        [Parameter(Mandatory)]
        [string]$ServicePrincipalId,

        [Parameter(Mandatory)]
        [string]$ResourceServicePrincipalId,

        [Parameter(Mandatory)]
        [string]$AppRoleId
    )

    # Check if assignment already exists
    $existingAssignments = Get-MgServicePrincipalAppRoleAssignment -ServicePrincipalId $ServicePrincipalId -ErrorAction SilentlyContinue
    $existing = $existingAssignments | Where-Object { $_.AppRoleId -eq $AppRoleId -and $_.ResourceId -eq $ResourceServicePrincipalId }

    if ($existing) {
        Write-Status "App role already assigned" -Type Warning
        return $existing
    }

    # Create new app role assignment (admin consent)
    Write-Status "Granting app role assignment..." -Type Info
    $assignment = New-MgServicePrincipalAppRoleAssignment `
        -ServicePrincipalId $ServicePrincipalId `
        -PrincipalId $ServicePrincipalId `
        -ResourceId $ResourceServicePrincipalId `
        -AppRoleId $AppRoleId

    Write-Status "App role assigned successfully" -Type Success
    return $assignment
}

function Export-EnvFile {
    <#
    .SYNOPSIS
        Exports configuration to a .env file.
    #>
    param(
        [Parameter(Mandatory)]
        [string]$OutputPath,

        [Parameter(Mandatory)]
        [hashtable]$Config
    )

    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

    $envContent = @"
# =============================================================================
# MCP Server with Proper Enterprise Authentication - Environment Configuration
# Generated by Setup-EntraIdAppRegistrations.ps1 on $timestamp
# =============================================================================

# -----------------------------------------------------------------------------
# Entra ID (Azure AD) Configuration
# -----------------------------------------------------------------------------
ENTRA_TENANT_ID=$($Config.TenantId)
ENTRA_AUTHORITY=https://login.microsoftonline.com/$($Config.TenantId)

# -----------------------------------------------------------------------------
# MCP Server Identity (as a Protected Resource)
# -----------------------------------------------------------------------------
MCP_SERVER_APP_ID=api://mcp-server-resource
MCP_SERVER_CLIENT_ID=$($Config.McpServerAppId)
MCP_SERVER_SCOPE_PREFIX=api://mcp-server-resource

# -----------------------------------------------------------------------------
# Authorization Requirements
# -----------------------------------------------------------------------------
REQUIRED_SCOPE=mcp.read mcp.write
REQUIRED_ROLE=MCP.ReadWrite.All

# -----------------------------------------------------------------------------
# Pre-registered Client IDs (from Entra ID App Registrations)
# -----------------------------------------------------------------------------
VSCODE_CLIENT_ID=$($Config.VsCodeClientId)
CLAUDE_DESKTOP_CLIENT_ID=$($Config.ClaudeDesktopClientId)
CLAUDE_CODE_CLIENT_ID=$($Config.ClaudeCodeClientId)
CHATGPT_CLIENT_ID=$($Config.ChatGptClientId)
GENERIC_CLIENT_ID=$($Config.GenericClientId)

# Confidential Client
CONFIDENTIAL_CLIENT_ID=$($Config.ConfidentialClientId)
CONFIDENTIAL_CLIENT_SECRET=$($Config.ConfidentialClientSecret)

# Service Principal
SERVICE_PRINCIPAL_CLIENT_ID=$($Config.ServicePrincipalClientId)
SERVICE_PRINCIPAL_CLIENT_SECRET=$($Config.ServicePrincipalClientSecret)

# -----------------------------------------------------------------------------
# MCP Server Configuration
# -----------------------------------------------------------------------------
DEPLOYMENT_MODE=fargate
MCP_SERVER_HOST=0.0.0.0
MCP_SERVER_PORT=8000
MCP_SERVER_BASE_URL=http://localhost:8000

# -----------------------------------------------------------------------------
# JWT Validation Configuration
# -----------------------------------------------------------------------------
JWT_CLOCK_SKEW_SECONDS=300
JWKS_CACHE_TTL_SECONDS=86400
VALIDATE_TOKEN_VERSION=true
ALLOWED_TOKEN_VERSIONS=2.0
ENFORCE_HTTPS_REDIRECTS=false

# -----------------------------------------------------------------------------
# DCR (Dynamic Client Registration) Emulation
# -----------------------------------------------------------------------------
ENABLE_DCR_ENDPOINT=true
DCR_RATE_LIMIT_PER_MINUTE=10

# -----------------------------------------------------------------------------
# Security Configuration
# -----------------------------------------------------------------------------
CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173,http://localhost:8080
CORS_ALLOW_CREDENTIALS=true
CORS_ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS
CORS_ALLOWED_HEADERS=*

# -----------------------------------------------------------------------------
# Logging Configuration
# -----------------------------------------------------------------------------
LOG_LEVEL=INFO
LOG_FORMAT=json
LOG_REQUESTS=true
LOG_JWT_CLAIMS=false

# -----------------------------------------------------------------------------
# Health Check Configuration
# -----------------------------------------------------------------------------
ENABLE_HEALTH_CHECK=true
HEALTH_CHECK_PATH=/health
READINESS_CHECK_PATH=/ready

# -----------------------------------------------------------------------------
# Development / Testing Configuration
# -----------------------------------------------------------------------------
DEBUG_MODE=false
ENABLE_SWAGGER=true
SWAGGER_UI_PATH=/docs
ENABLE_MOCK_AUTH=false
"@

    Set-Content -Path $OutputPath -Value $envContent -Encoding UTF8
    Write-Status "Environment file written to: $OutputPath" -Type Success
}

# =============================================================================
# Main Script Execution
# =============================================================================

try {
    Write-Host ""
    Write-Host "========================================" -ForegroundColor Cyan
    Write-Host "  MCP Enterprise Auth - Entra ID Setup" -ForegroundColor Cyan
    Write-Host "========================================" -ForegroundColor Cyan
    Write-Host ""

    # Determine output path
    if (-not $OutputEnvFile) {
        $scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
        $OutputEnvFile = Join-Path (Split-Path -Parent $scriptDir) ".env"
    }

    # Step 1: Connect to Microsoft Graph
    Write-Status "Connecting to Microsoft Graph..." -Type Info

    $scopes = @(
        "Application.ReadWrite.All",
        "AppRoleAssignment.ReadWrite.All",
        "Directory.ReadWrite.All"
    )

    if ($TenantId) {
        Connect-MgGraph -Scopes $scopes -TenantId $TenantId -NoWelcome
    }
    else {
        Connect-MgGraph -Scopes $scopes -NoWelcome
    }

    # Get tenant info
    $context = Get-MgContext
    $TenantId = $context.TenantId
    Write-Status "Connected to tenant: $TenantId" -Type Success
    Write-Host ""

    # Step 2: Create MCP Server Resource (must be first)
    Write-Host "--- Creating MCP Server Resource API ---" -ForegroundColor Cyan
    $mcpServer = New-McpServerResource -Prefix $AppNamePrefix
    Write-Host ""

    # Step 3: Create Public Clients
    Write-Host "--- Creating Public Clients ---" -ForegroundColor Cyan

    $vsCodeClient = New-PublicMcpClient `
        -DisplayName "$AppNamePrefix VS Code Client" `
        -RedirectUris @("vscode://mcp-auth/callback", "vscode-insiders://mcp-auth/callback", "http://localhost:8080/callback") `
        -McpServerAppId $mcpServer.Application.AppId

    $claudeDesktopClient = New-PublicMcpClient `
        -DisplayName "$AppNamePrefix Claude Desktop Client" `
        -RedirectUris @("claude://mcp-auth/callback") `
        -McpServerAppId $mcpServer.Application.AppId

    $claudeCodeClient = New-PublicMcpClient `
        -DisplayName "$AppNamePrefix Claude Code Client" `
        -RedirectUris @("http://localhost:8080/callback", "http://127.0.0.1:8080/callback") `
        -McpServerAppId $mcpServer.Application.AppId

    $chatGptClient = New-PublicMcpClient `
        -DisplayName "$AppNamePrefix ChatGPT Client" `
        -RedirectUris @("https://chatgpt.com/oauth/callback", "https://chat.openai.com/oauth/callback") `
        -McpServerAppId $mcpServer.Application.AppId

    $genericClient = New-PublicMcpClient `
        -DisplayName "$AppNamePrefix Generic Client" `
        -RedirectUris @("http://localhost:8080/callback", "http://127.0.0.1:8080/callback") `
        -McpServerAppId $mcpServer.Application.AppId

    Write-Host ""

    # Step 4: Create Confidential Client
    Write-Host "--- Creating Confidential Client ---" -ForegroundColor Cyan
    $confidentialClient = New-ConfidentialMcpClient `
        -Prefix $AppNamePrefix `
        -McpServerAppId $mcpServer.Application.AppId `
        -ForceNewSecret:$Force
    Write-Host ""

    # Step 5: Create Service Principal Client
    Write-Host "--- Creating Service Principal Client ---" -ForegroundColor Cyan
    $servicePrincipalClient = New-ServicePrincipalMcpClient `
        -Prefix $AppNamePrefix `
        -McpServerAppId $mcpServer.Application.AppId `
        -ForceNewSecret:$Force
    Write-Host ""

    # Step 6: Grant admin consent for app role
    Write-Host "--- Granting Admin Consent for App Role ---" -ForegroundColor Cyan
    Grant-AppRoleAssignment `
        -ServicePrincipalId $servicePrincipalClient.ServicePrincipal.Id `
        -ResourceServicePrincipalId $mcpServer.ServicePrincipal.Id `
        -AppRoleId $script:McpReadWriteAllRoleId
    Write-Host ""

    # Step 7: Generate .env file
    Write-Host "--- Generating Environment File ---" -ForegroundColor Cyan
    $config = @{
        TenantId                     = $TenantId
        McpServerAppId               = $mcpServer.Application.AppId
        VsCodeClientId               = $vsCodeClient.Application.AppId
        ClaudeDesktopClientId        = $claudeDesktopClient.Application.AppId
        ClaudeCodeClientId           = $claudeCodeClient.Application.AppId
        ChatGptClientId              = $chatGptClient.Application.AppId
        GenericClientId              = $genericClient.Application.AppId
        ConfidentialClientId         = $confidentialClient.Application.AppId
        ConfidentialClientSecret     = if ($confidentialClient.ClientSecret) { $confidentialClient.ClientSecret } else { "<existing-secret-not-shown>" }
        ServicePrincipalClientId     = $servicePrincipalClient.Application.AppId
        ServicePrincipalClientSecret = if ($servicePrincipalClient.ClientSecret) { $servicePrincipalClient.ClientSecret } else { "<existing-secret-not-shown>" }
    }

    Export-EnvFile -OutputPath $OutputEnvFile -Config $config
    Write-Host ""

    # Summary
    Write-Host "========================================" -ForegroundColor Green
    Write-Host "  Setup Complete!" -ForegroundColor Green
    Write-Host "========================================" -ForegroundColor Green
    Write-Host ""
    Write-Host "App Registration Summary:" -ForegroundColor Cyan
    Write-Host "  MCP Server Resource:      $($mcpServer.Application.AppId)"
    Write-Host "  VS Code Client:           $($vsCodeClient.Application.AppId)"
    Write-Host "  Claude Desktop Client:    $($claudeDesktopClient.Application.AppId)"
    Write-Host "  Claude Code Client:       $($claudeCodeClient.Application.AppId)"
    Write-Host "  ChatGPT Client:           $($chatGptClient.Application.AppId)"
    Write-Host "  Generic Client:           $($genericClient.Application.AppId)"
    Write-Host "  Confidential Client:      $($confidentialClient.Application.AppId)"
    Write-Host "  Service Principal Client: $($servicePrincipalClient.Application.AppId)"
    Write-Host ""
    Write-Host "Environment file: $OutputEnvFile" -ForegroundColor Yellow
    Write-Host ""

    if ($confidentialClient.ClientSecret -or $servicePrincipalClient.ClientSecret) {
        Write-Host "IMPORTANT: Client secrets have been written to the .env file." -ForegroundColor Yellow
        Write-Host "           Store them securely and do not commit to source control!" -ForegroundColor Yellow
        Write-Host ""
    }

    Write-Host "Next steps:" -ForegroundColor Cyan
    Write-Host "  1. Review the generated .env file"
    Write-Host "  2. Verify app registrations in Azure Portal"
    Write-Host "  3. Run tests: ./scripts/run-all-tests.sh"
    Write-Host ""
}
catch {
    Write-Status "Script failed: $_" -Type Error
    Write-Host $_.ScriptStackTrace -ForegroundColor Red
    throw
}
finally {
    Disconnect-MgGraph -ErrorAction SilentlyContinue | Out-Null
}
